apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: registry.cn-qingdao.aliyuncs.com/ky-zadig/examplevotingapp_worker:latest
        #image: dockersamples/examplevotingapp_worker
        name: worker-e2e
